quarkus:
  http:
    port: 8081

  log:
    level: INFO
    console:
      enable: true

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      db-version: 14
      username: user
      password: postgres
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/quarkus_dev

    hibernate-orm:
      schema-management:
        strategy: update

"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      db-version: 14
      username: user
      password: postgres
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/quarkus_test

    hibernate-orm:
      schema-management:
        strategy: drop-and-create

"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      db-version: 14
      username: user
      password: postgres
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/quarkus_prod

    hibernate-orm:
      schema-management:
        strategy: none
