quarkus:
  http:
    port: 8081

  log:
    level: INFO
    console:
      enable: true

  devservices:
    enabled: false

  otel:
    metrics:
      enabled: false

"%dev":
  quarkus:
    datasource:
      db-kind: postgresql
      db-version: ${POSTGRES_VERSION}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/${POSTGRES_DATABASE}

    hibernate-orm:
      schema-management:
        strategy: ${POSTGRES_STRATEGY}

"%test":
  quarkus:
    datasource:
      db-kind: postgresql
      db-version: ${POSTGRES_VERSION}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/${POSTGRES_DATABASE}

    hibernate-orm:
      schema-management:
        strategy: ${POSTGRES_STRATEGY}

"%prod":
  quarkus:
    datasource:
      db-kind: postgresql
      db-version: ${POSTGRES_VERSION}
      username: ${POSTGRES_USER}
      password: ${POSTGRES_PASSWORD}
      reactive:
        url: vertx-reactive:postgresql://localhost:5432/${POSTGRES_DATABASE}

    hibernate-orm:
      schema-management:
        strategy: ${POSTGRES_STRATEGY}
